with src_opportunity as (SELECT
    *
FROM
    {{ ref('src_opportunity') }}
)
SELECT
    Id	,
    AccountId	,
    RecordTypeId	,
    Name	,
    StageName	,
    Amount	,
    Probability	,
    CloseDate	,
    Type	,
    NextStep	,
    ForecastCategory	,
    CurrencyIsoCode	,
    HasOpportunityLineItem	,
    OwnerId	,
    CreatedDate	,
    CreatedById	,
    LastModifiedDate	,
    FiscalQuarter	,
    FiscalYear	,
    Fiscal	,
    Enterprise_License_Agreement__c	,
    Opportunity_Source__c	,
    BU_Name__c	,
    Stage_Prior_to_Lost_Label__c	,
    Partner_Transaction_Type__c	,
    Partner_Name__c	,
    Comment__c	,
    Original_Correct_Opportunity_ID__c	,
    Fall_Out_Reason__c	,
    Support_Access_Code__c	,
    Opportunity_ID__c	,
    Agreement__c	,
    Catalog_line_service__c	,
    Number_Of_Products__c	,
    Region__c	,
    Stage_Probability__c	,
    Cloud_Gross_Amount__c	,
    License_Gross_Amount__c	,
    Maintenance_Gross_Amount__c	,
    Service_Gross_Amount__c	,
    Deal_Reviewed__c	,
    Deal_Review_Comment__c	,
    Account_NAS__c	,
    Maintenance_Ratio__c	,
    Opportunity_URL__c	,
    Cloud_Amount_ACV__c	,
    Carve_out__c	,
    Partner_Role__c	,
    SBQQ__Ordered__c	,
    SBQQ__Contracted__c	,
    Primary_Quote_Start_Date__c	,
    Axway_Account_ID__c	,
    UpSell_Annual_Value__c	,
    Annual_Renewal_Initial_Amount__c	,
    DownSell_Annual_Amount__c	,
    Opportunity_Type__c	,
    Risk__c	,
    Term__c	,
    Next_Steps__c	,
    Recurring_Revenue_Type__c	,
    Number_of_Opportunity_Assessment__c	,
    Signature__c	,
    Recurring_Annual_Amount__c	,
    Recurring_Annual_Base__c	,
    Recurring_Annual_Base_override__c	,
    Recurring_Annual_Delta__c	,
    Recurring_Total_Amount__c	,
    Recurring_Total_Base__c	,
    Recurring_Total_Base_override__c	,
    Recurring_Total_Delta__c	,
    Revenue_Recognition_Date__c	,
    Related_Opp_ID__c	,
    Axway_Managed__c	,
    LTCV_Booking__c	,
    Contract_Supersede__c	,
    Partial_Cancelation__c	,
    Activated_Order__c	
FROM
    src_opportunity
WHERE
    isDeleted='false' AND
    (Fall_Out_Reason__c not in ('Data Cleanup', 'Duplicate', 'Migration – Bad Data') or Fall_Out_Reason__c is null) AND
    upper(name) not like '%DO NOT USE%' AND
    upper(name) not like '%SCHUMANN EN%' AND
    ForecastCategory = 'Closed' AND
    extract(year from to_date(closedate, 'YYYY-MM-DD')) >= 2018
